import type { PortfolioContent } from "@/types/content";

/**
 * English content (secondary locale).
 * Comprehensive, authentic, and balanced profile of Ower Frank Lopez Arela.
 * Mirrors the es.ts structure field-for-field; typecheck enforces parity.
 */
export const en: PortfolioContent = {
  meta: {
    title: "Ower Frank Lopez Arela — Backend & Data Engineer",
    description:
      "9th-semester Systems Engineering student at UNSA and Backend Developer. Building REST APIs, data pipelines, and cloud services with Java, Spring Boot, Node.js, and Python.",
    ogAlt:
      "Portfolio of Ower Frank Lopez Arela — Backend & Data Engineer",
    keywords: [
      "Backend Developer",
      "Data Engineer",
      "Data Engineering",
      "Java",
      "Spring Boot",
      "NestJS",
      "Python",
      "PostgreSQL",
      "Docker",
      "Arequipa",
      "Peru",
    ],
  },

  nav: {
    work: "Projects",
    expertise: "Expertise",
    experience: "Experience",
    about: "About",
    contact: "Contact",
    cta: "Let's talk",
    menuOpen: "Open menu",
    menuClose: "Close menu",
    statusText: "Open to opportunities",
    soundOn: "Sound FX Enabled",
    soundOff: "Sound FX Muted",
  },

  intro: {
    status: "Available for Junior Data Engineer & Backend roles",
    kicker: "BACKEND ENGINEERING & DATA PIPELINES · AREQUIPA, PERU",
    titleLines: ["Backend Developer", "& Data Engineer"],
    titleAccent: "building reliable software.",
    description:
      "9th-semester Systems Engineering student at UNSA and Backend Developer at Fundación CALMA. Focused on REST API design, database optimization, data pipelines, and cloud deployments.",
    primaryCta: "View projects",
    primaryTarget: "#work",
    secondaryCta: "Copy email",
    copiedFeedback: "Email copied to clipboard.",
    scrollCue: "Explore my projects and background",
    frameLabel: "STATUS · ACTIVE",
  },

  marquee: [
    { name: "Java 17", category: "Backend" },
    { name: "Spring Boot 3.4", category: "Backend" },
    { name: "NestJS", category: "Backend" },
    { name: "Node.js", category: "Backend" },
    { name: "Python 3.12", category: "Data" },
    { name: "PostgreSQL", category: "Data" },
    { name: "MongoDB", category: "Data" },
    { name: "SQL Server", category: "Data" },
    { name: "MySQL", category: "Data" },
    { name: "Docker", category: "DevOps" },
    { name: "Oracle Cloud", category: "Cloud" },
    { name: "AWS", category: "Cloud" },
    { name: "Google Cloud", category: "Cloud" },
    { name: "ONNX Runtime", category: "AI" },
  ],

  mission: {
    kicker: "ENGINEERING APPROACH",
    headingLead: "Solid architecture,",
    headingAccent: "value-driven solutions.",
    paragraphs: [
      "System quality is not just measured by delivered features, but by stability, data consistency, and long-term maintainability in production. Every API contract and data workflow must be designed with clarity and reliability.",
      "My experience spans developing production backend services with Java and Node.js, managing operational data systems for 2,000+ applicants in evaluation processes, and integrating Machine Learning models.",
    ],
    facts: [
      { key: "Profile", value: "Backend & Data Engineering" },
      { key: "Specialty", value: "REST APIs, SQL & ETL Pipelines" },
      { key: "Methodology", value: "Clean Architecture & Scrum" },
      { key: "Location", value: "Arequipa, Peru · UTC-5" },
    ],
  },

  work: {
    kicker: "ENGINEERING CATALOG",
    heading: "Projects and software in production",
    description:
      "Explore the complete catalog of auditable repositories: high-concurrency backend services, real-time data pipelines, applied artificial intelligence, and mobile systems.",
    filterLabels: {
      all: "All",
      backend: "Backend & APIs",
      data: "Data & Machine Learning",
      mobile: "Mobile & Native Systems",
    },
    viewModes: {
      grid: "Bento Showroom",
      carousel: "Focus Carousel",
    },
    featuredLabel: "Flagship Project",
    featured: {
      flag: "Featured",
      category: "Enterprise ML Platform & Backend",
      title: "ChurnInsight",
      summary:
        "Customer churn prediction platform with ML inference embedded directly into the backend via ONNX Runtime, eliminating network overhead and external service dependencies.",
      image: "/assets/projects/churn-insight.jpg",
      tags: ["Java 17", "Spring Boot 3.4", "ONNX Runtime", "Random Forest", "MySQL", "JWT"],
      note: "By executing the ONNX model within the same Spring Boot process, P99 latency dropped from 2,000 ms to 20 ms. Includes JWT authentication, versioned SQL migrations, and model explainability (XAI) with 96% recall.",
      metrics: [
        { value: "96%", label: "Recall (Random Forest)", highlight: true },
        { value: "20 ms", label: "Inference P99 (ONNX)", highlight: true },
        { value: "99%", label: "Latency reduction" },
        { value: "0", label: "External ML calls" },
      ],
      links: [
        { label: "View Backend on GitHub", href: "https://github.com/OwerLopez/ChurnInsight-Backend", external: true },
        { label: "View Dashboard on GitHub", href: "https://github.com/OwerLopez/ChurnInsight-Frontend", external: true },
        { label: "View architecture", href: "#architecture" },
      ],
    },
    catalogLabel: "Complete catalog of auditable repositories",
    projects: [
      {
        index: "01",
        category: "data",
        categoryLabel: "Data & ML",
        tone: "violet",
        badge: "⚡ Real-Time · 28.7 FPS",
        title: "VisionTransit AI",
        repoName: "VisionTransit_AI",
        githubUrl: "https://github.com/OwerLopez/VisionTransit_AI",
        image: "/assets/projects/vision-transit.jpg",
        description:
          "Real-time computer vision pipeline for public transit monitoring. Decoupled 6-layer architecture with FastAPI, YOLO11, and WebSockets, sustaining 28.7 FPS on CPU.",
        metrics: [
          { label: "Throughput", value: "28.7 FPS (CPU)" },
          { label: "Architecture", value: "6 modular layers" },
        ],
        tags: ["Python 3.12", "FastAPI", "YOLO11", "WebSockets", "Docker"],
        year: "2025",
      },
      {
        index: "02",
        category: "backend",
        categoryLabel: "Backend & APIs",
        tone: "gold",
        badge: "🏆 1st Place IBM Hackathon",
        title: "NEXIA 2026 (WeWin TI)",
        repoName: "wewinti-fullstack-app",
        githubUrl: "https://github.com/OwerLopez/wewinti-fullstack-app",
        image: "/assets/projects/nexia-ai.jpg",
        description:
          "1st place in the 'Build with AI' Hackathon (IBM, GDG Arequipa, and JAKU UNSA). Educational innovation MVP built in <48h with NestJS architecture, protected services layer, and generative AI APIs.",
        metrics: [
          { label: "Turnaround", value: "< 48 hours" },
          { label: "Award", value: "1st Place Winner" },
        ],
        tags: ["Node.js", "NestJS", "TypeScript", "React 19", "AI APIs"],
        year: "2026",
      },
      {
        index: "03",
        category: "mobile",
        categoryLabel: "Mobile & AI",
        tone: "cyan",
        badge: "🤖 Gemini AI Integrated",
        title: "AI Life OS Mobile",
        repoName: "AI_Life_OS_mobile",
        githubUrl: "https://github.com/OwerLopez/AI_Life_OS_mobile",
        image: "/assets/projects/ai-life-os.jpg",
        description:
          "Native Android application centralizing personal notes and tasks by leveraging Google Gemini AI for smart summarization and classification. Built with Clean Architecture, Jetpack Compose, and Offline-First sync (Room + Firestore).",
        metrics: [
          { label: "Architecture", value: "Clean Arch + MVI" },
          { label: "Persistence", value: "Offline-First (Room)" },
        ],
        tags: ["Kotlin", "Jetpack Compose", "Gemini AI", "Room", "Firestore"],
        year: "2026",
      },
      {
        index: "04",
        category: "backend",
        categoryLabel: "Backend & DevOps",
        tone: "emerald",
        badge: "🐳 Telemetry & Docker",
        title: "AI Workflow Recorder",
        repoName: "ai-workflow-recorder",
        githubUrl: "https://github.com/OwerLopez/ai-workflow-recorder",
        image: "/assets/projects/workflow-recorder.jpg",
        description:
          "End-to-end platform for silent browser telemetry and deterministic workflow automation. Includes browser extension, Python ingestion backend, and containerized Docker dashboard.",
        metrics: [
          { label: "Deployment", value: "Docker Compose" },
          { label: "Type", value: "Full-Stack Telemetry" },
        ],
        tags: ["Python", "FastAPI", "Chrome Extension", "Docker", "REST APIs"],
        year: "2026",
      },
      {
        index: "05",
        category: "data",
        categoryLabel: "Data Engineering",
        tone: "blue",
        badge: "📊 Data Science & Pipeline",
        title: "Telecom Churn ML Pipeline",
        repoName: "telecom-churn-ml-pipeline",
        githubUrl: "https://github.com/OwerLopez/telecom-churn-ml-pipeline",
        image: "/assets/projects/telecom-churn.jpg",
        description:
          "Comprehensive data analysis and machine learning pipeline for customer churn prediction: structured data wrangling, feature engineering, class balancing, and model benchmarking.",
        metrics: [
          { label: "Methodology", value: "EDA + Scikit-Learn" },
          { label: "Output", value: "Exported Models" },
        ],
        tags: ["Python", "Pandas", "Scikit-Learn", "NumPy", "EDA"],
        year: "2025",
      },
      {
        index: "06",
        category: "backend",
        categoryLabel: "Backend & Testing",
        tone: "violet",
        badge: "🧪 Comprehensive Test Suite",
        title: "NovaChef Restaurant Platform",
        repoName: "novachef-restaurant-platform",
        githubUrl: "https://github.com/OwerLopez/novachef-restaurant-platform",
        image: "/assets/projects/novachef.jpg",
        description:
          "Full-stack restaurant management platform with role-based access control, order processing, payment gateway, and inventory. Features an extensive automated test suite with PyTest (unit, integration, security, and BVA/EP boundary testing).",
        metrics: [
          { label: "QA Coverage", value: "Unit + Integration + Security" },
          { label: "Security", value: "Role-Based Access" },
        ],
        tags: ["Python", "Django", "PyTest", "PostgreSQL", "QA Testing"],
        year: "2026",
      },
      {
        index: "07",
        category: "mobile",
        categoryLabel: "C++ Systems",
        tone: "amber",
        badge: "🏛️ Desktop GIS & Analytics",
        title: "Qt Water Resources System",
        repoName: "qt-water-resources-system",
        githubUrl: "https://github.com/OwerLopez/qt-water-resources-system",
        image: "/assets/projects/qt-water.jpg",
        description:
          "High-performance desktop information system for water resource management: technical administration of basins, dams, and canals with graphical data views and hydrological models in C++ and Qt Framework.",
        metrics: [
          { label: "Environment", value: "Qt / Native C++" },
          { label: "Domain", value: "Hydro-Informatics" },
        ],
        tags: ["C++", "Qt Framework", "Desktop GUI", "Data Modeling"],
        year: "2024",
      },
      {
        index: "08",
        category: "mobile",
        categoryLabel: "Mobile Native",
        tone: "cyan",
        badge: "📱 Clean Architecture",
        title: "Gestor Tareas Pro",
        repoName: "GestorTareasPro",
        githubUrl: "https://github.com/OwerLopez/GestorTareasPro",
        image: "/assets/projects/gestor-tareas.jpg",
        description:
          "Native Android task and habit manager with Jetpack Compose and Clean Architecture. Offline-first architecture with Room SQLite database, immutable progress calendar, and streak-based motivation system.",
        metrics: [
          { label: "Architecture", value: "Clean Arch (Domain/Data/UI)" },
          { label: "Database", value: "Room SQLite" },
        ],
        tags: ["Kotlin", "Jetpack Compose", "Room", "Coroutines", "Flow"],
        year: "2026",
      },
    ],
    matrixTitle: "Executive technical repository matrix",
    matrixHeaders: {
      project: "Project / Repo",
      domain: "Domain",
      stack: "Core Stack",
      result: "Key Metric / Result",
      role: "Role",
      year: "Year",
    },
    matrix: [
      {
        project: "ChurnInsight",
        domain: "ML & Backend JVM",
        stack: "Java 17 · Spring Boot · ONNX",
        result: "Latency 2000ms → 20ms · Recall 96%",
        role: "Backend + Data Science",
        year: "2025",
      },
      {
        project: "VisionTransit AI",
        domain: "Computer Vision / Data",
        stack: "Python · FastAPI · YOLO11",
        result: "28.7 FPS real-time · 6 layers",
        role: "Data Engineer + ML",
        year: "2025",
      },
      {
        project: "NEXIA 2026 (WeWin TI)",
        domain: "Backend & Generative AI",
        stack: "Node.js · NestJS · LLM APIs",
        result: "MVP in < 48h · 1st Place Hackathon",
        role: "Backend Lead",
        year: "2026",
      },
      {
        project: "AI Life OS",
        domain: "Mobile Native & AI",
        stack: "Kotlin · Jetpack Compose · Gemini",
        result: "Offline-First + AI Summaries",
        role: "Android Developer",
        year: "2026",
      },
      {
        project: "AI Workflow Recorder",
        domain: "Backend & Telemetry",
        stack: "Python · FastAPI · Extension",
        result: "Automation & Docker Compose",
        role: "Full-Stack Engineer",
        year: "2026",
      },
      {
        project: "NovaChef Platform",
        domain: "Backend & Testing QA",
        stack: "Python · Django · PyTest",
        result: "BVA/EP Test Suite + Security",
        role: "Backend Developer",
        year: "2026",
      },
      {
        project: "Qt Water Resources",
        domain: "Desktop C++ Systems",
        stack: "C++ · Qt Framework · GUI",
        result: "Hydrological basin modeling",
        role: "C++ Software Engineer",
        year: "2024",
      },
      {
        project: "Gestor Tareas Pro",
        domain: "Mobile Native Android",
        stack: "Kotlin · Jetpack Compose · Room",
        result: "Clean Arch + Local Persistence",
        role: "Android Developer",
        year: "2026",
      },
    ],
  },

  architecture: {
    kicker: "DATA & ML ARCHITECTURE",
    headingLead: "Data lifecycle:",
    headingAccent: "from ingestion to production.",
    description:
      "Five-stage pipeline structure engineered for data integrity, low latency, and high maintainability.",
    stages: [
      {
        index: "E1",
        label: "Data Sources",
        detail: "Transactional databases, NoSQL and external APIs",
        tech: "PostgreSQL · MySQL · SQL Server · MongoDB · APIs",
        power: "INGESTION 100%",
      },
      {
        index: "E2",
        label: "ETL Processing",
        detail: "Extraction, cleaning, type safety and transformation",
        tech: "Python · Pandas · SQL · BULK INSERT",
        power: "PROCESSING",
      },
      {
        index: "E3",
        label: "Storage & Quality",
        detail: "Relational modeling, optimized queries and integrity",
        tech: "Logical/Physical modeling · CTEs · Window Functions",
        power: "INTEGRITY",
      },
      {
        index: "E4",
        label: "ML Inference",
        detail: "Trained models and low-latency in-memory prediction",
        tech: "NumPy · Random Forest · ONNX Runtime · XAI",
        power: "ONNX INFERENCE",
      },
      {
        index: "E5",
        label: "Service Layer",
        detail: "Secure consumption via REST APIs and dashboards",
        tech: "Spring Boot · JWT · Swagger · Power BI",
        power: "PRODUCTION API",
      },
    ],
    note: "Embedded inference: the model runs in-process inside the backend, achieving 20 ms P99 latency with zero external network overhead.",
  },

  stack: {
    kicker: "TECH STACK & DOMAINS",
    heading: "Core technologies and tools",
    description:
      "Tools I use to design and build robust backend services, data engineering pipelines, and cloud integrations.",
    groups: [
      { name: "Backend", glow: "flame", items: ["Java 17", "Spring Boot 3.4", "NestJS", "Node.js", "REST APIs · Swagger"] },
      { name: "Data", glow: "magenta", items: ["PostgreSQL", "MySQL · SQL Server", "MongoDB", "Pandas · NumPy", "Power BI"] },
      { name: "Cloud & DevOps", glow: "flame", items: ["Oracle Cloud (OCI)", "AWS EC2 · S3", "Google Cloud", "Docker", "Git"] },
      { name: "AI / Machine Learning", glow: "violet", items: ["Python 3.12", "ONNX Runtime", "Random Forest", "XAI"] },
    ],
    note: "Hands-on experience in backend design, data management, cloud deployments, and agile methodologies.",
  },

  journey: {
    kicker: "EXPERIENCE & BACKGROUND",
    heading: "Professional experience and leadership",
    description:
      "Career background focused on production backend development, high-throughput data operations, and student leadership.",
    items: [
      {
        period: "Feb 2026 → Present",
        title: "Backend Developer (Intern) — Fundación CALMA",
        description:
          "Development and maintenance of backend services with REST APIs, business logic, JWT authentication, and access control. Management and optimization of PostgreSQL, MySQL, SQL Server, and MongoDB databases under Scrum methodology.",
        tone: "flame",
      },
      {
        period: "2024 — 2025",
        title: "IT Operator & Data Operations — ESAN / PRONABEC",
        description:
          "IT support and data verification for 2,000+ applicants during the National Preselection Exam (Beca 18), operating evaluation platforms under high confidentiality and data integrity standards.",
        tone: "glow",
      },
      {
        period: "2024 — 2025",
        title: "ACM Chapter Secretary · Top 20% Rank (Quinto Superior)",
        description:
          "Secretary on the board of the ACM Student Chapter UNSA, coordinating technical AI and competitive programming workshops. Top 20% academic rank in Systems Engineering at UNSA.",
        tone: "muted",
      },
    ],
  },

  github: {
    kicker: "GITHUB ACTIVITY",
    heading: "Repositories and source code activity",
    description:
      "Queried in real time from the GitHub API to showcase recent activity and public repositories.",
    metrics: [
      { label: "Public repos" },
      { label: "Followers" },
      { label: "Latest commit" },
    ],
    viewAll: "View repositories on GitHub",
    updatedLabel: "Live update",
    errorText: "Could not reach the GitHub API at this moment.",
    loadingText: "Querying live GitHub activity…",
    logTitle: "Activity log",
    logEmpty: "Awaiting API response…",
  },

  credentials: {
    kicker: "PROFESSIONAL CREDENTIALS",
    heading: "Official verified certifications",
    description:
      "Accreditations issued by industry-leading providers in cloud computing, database architecture, and data science.",
    credentialsLabel: "Verified credentials on Credly",
    credentials: [
      { name: "Oracle Cloud Infrastructure 2025 Foundations", issuer: "Oracle", acronym: "OCI", href: "https://www.credly.com/search?q=Oracle%20Cloud%20Infrastructure%202025%20Foundations", glow: "flame" },
      { name: "Oracle APEX Cloud Developer Professional", issuer: "Oracle", acronym: "APEX", href: "https://www.credly.com/search?q=Oracle%20APEX%20Cloud%20Developer%20Professional", glow: "flame" },
      { name: "Google Cloud Computing Foundations", issuer: "Google Cloud", acronym: "GCP", href: "https://www.credly.com/search?q=Google%20Cloud%20Computing%20Foundations", glow: "magenta" },
      { name: "AWS Academy Graduate — Cloud Foundations", issuer: "AWS", acronym: "AWS", href: "https://www.credly.com/search?q=AWS%20Academy%20Graduate%20—%20Cloud%20Foundations", glow: "magenta" },
      { name: "ONE Tech — Data Science (440h)", issuer: "Alura Latam", acronym: "ONE", href: "https://www.credly.com/search?q=ONE%20Tech%20—%20Data%20Science%20(440h)", glow: "flame" },
      { name: "Microsoft SQL Server Advanced Specialization", issuer: "Datux Peru", acronym: "SQL", href: "https://www.credly.com/search?q=Especializacion%20Microsoft%20SQL%20Server%20(avanzado)", glow: "violet" },
    ],
    verifyCta: "Verify on Credly",
  },

  philosophy: {
    kicker: "ABOUT ME & PERSONAL PROFILE",
    headingLead: "Behind the code:",
    headingAccent: "vision, discipline & mindset.",
    description:
      "Rigorous Systems Engineering background from UNSA, hands-on experience building high-performance backend systems, and passion for algorithms and clean architecture.",
    bioHeading: "Ower Frank Lopez Arela",
    bioRole: "Backend & Data Engineer · UNSA (Top 20% Rank)",
    bioLocation: "Arequipa, Peru",
    bioBadge: "UNSA Top 20% · Class of 2026",
    bioText: [
      "Final-year Systems Engineering student at Universidad Nacional de San Agustín (UNSA), ranked in the Top 20% (Quinto Superior), and Backend Developer at Fundación CALMA.",
      "Passionate about solving performance bottlenecks, designing strict API contracts, and transforming complex data workflows into reliable services. As Secretary of the ACM Student Chapter UNSA, I foster technical education in algorithms, data structures, and emerging technologies.",
    ],
    facetsLabel: "Key Profile Facts",
    facets: [
      { label: "Languages", value: "Spanish (Native) · English (Technical B2)", detail: "Fluent technical reading & writing" },
      { label: "Core Interests", value: "Low-Latency Backend & Data Streaming", detail: "Distributed systems & in-memory ML inference" },
      { label: "Academic Standing", value: "Top 20% Class Rank (Quinto Superior)", detail: "Systems Engineering School · UNSA" },
      { label: "Location", value: "Arequipa, Peru (UTC-5)", detail: "Available for remote or hybrid engineering roles" },
    ],
    hobbiesKicker: "PASSIONS & FOCUS",
    hobbiesLabel: "Mindset, Deep Work & Campus Life",
    hobbiesDescription: "The disciplines, habits, and passions that fuel my analytical ability, problem-solving speed, and deep concentration.",
    hobbies: [
      {
        id: "chess",
        name: "Tactical Chess",
        category: "Strategy & Thinking",
        description: "Solving tactical puzzles and rapid games. Applying positional calculations and forward move anticipation to software architecture decisions.",
        tag: "Strategy",
        accent: "amber",
      },
      {
        id: "music",
        name: "Synthwave & Deep Work",
        category: "Music & Focus",
        description: "Enthusiast of Synthwave, Lo-Fi, and retro-futuristic soundscapes. My essential daily catalyst for entering flow states and maintaining deep focus when coding.",
        tag: "Flow State",
        accent: "violet",
      },
      {
        id: "competitive-coding",
        name: "Algorithms & ACM Mentorship",
        category: "Computer Science",
        description: "Continuous practice on LeetCode and ACM Chapter UNSA workshops: graphs, complex data structures, and asymptotic time-space efficiency.",
        tag: "Algorithms",
        accent: "cyan",
      },
      {
        id: "photography-campus",
        name: "Photography & UNSA Life",
        category: "Campus & Surroundings",
        description: "Capturing the energy across the San Agustín campus, the iconic Arequipa landscape beneath Mount Misti, and hackathon sprints with teammates.",
        tag: "UNSA / Arequipa",
        accent: "emerald",
      },
    ],
    footerMotto: "Discipline · Strategy · Focus",
    footerTag: "UNSA 2026",
  },

  contact: {
    kicker: "DIRECT COMMUNICATION",
    headingLead: "Let's start a",
    headingAccent: "professional conversation.",
    description:
      "Available for Junior Data Engineer and Backend Developer opportunities. If you are looking for a motivated, proactive engineer focused on delivering quality software, feel free to reach out.",
    terminalTitle: "contact@owerlopez.dev",
    greeting: "init — contact",
    context:
      "Open to opportunities in backend development, data engineering pipelines, and cloud software projects.",
    request:
      "You can send me an email directly or connect with me on LinkedIn.",
    emailLabel: "Direct email",
    copyLabel: "Copy",
    copiedFeedback: "Copied",
    responseTime: "Response in < 24 h on business days",
    cards: [
      { label: "GitHub", value: "github.com/OwerLopez", href: "https://github.com/OwerLopez" },
      { label: "LinkedIn", value: "linkedin.com/in/owerlopez", href: "https://www.linkedin.com/in/owerlopez/" },
      { label: "Credly", value: "Verified credentials", href: "https://www.credly.com/users/ower-frank-lopez-arela" },
    ],
    channels: [
      { kind: "link", label: "GitHub", handle: "@OwerLopez", href: "https://github.com/OwerLopez", external: true },
      { kind: "link", label: "LinkedIn", handle: "Ower Frank Lopez Arela", href: "https://www.linkedin.com/in/owerlopez/", external: true },
      { kind: "link", label: "Credly", handle: "credly.com", href: "https://www.credly.com/users/ower-frank-lopez-arela", external: true },
      { kind: "location", label: "Location", handle: "Arequipa, Peru · UTC-5", href: "https://maps.google.com/?q=Arequipa+Peru", external: true },
    ],
  },

  footer: {
    copyright: "© 2026 Ower Frank Lopez Arela",
    rights: "All rights reserved.",
    tagline: "Backend · Data · Cloud · AI — Arequipa, Peru (16.40°S 71.53°W)",
    credit: "Developed by Ower F. Lopez Arela",
    location: "Arequipa, Peru",
    timezone: "UTC-5",
    systemStatus: {
      availabilityLabel: "availability",
      availabilityValue: "Available for hire",
      zoneLabel: "zone",
      modeLabel: "status",
      modeValue: "open to opportunities",
    },
    navLabel: "Main navigation",
    navTitle: "Sections",
    navItems: {
      work: "Projects",
      expertise: "Expertise",
      experience: "Experience",
      about: "About",
      contact: "Contact",
    },
    contactTitle: "Channels",
    contactItems: [
      { href: "https://github.com/OwerLopez", label: "github.com/OwerLopez", external: true },
      { href: "https://www.linkedin.com/in/owerlopez/", label: "linkedin.com/in/owerlopez", external: true },
      { href: "https://www.credly.com/users/ower-frank-lopez-arela", label: "credly.com — Credentials", external: true },
    ],
    githubLabel: "GitHub",
    linkedinLabel: "LinkedIn",
    credlyLabel: "Credly",
  },
};
